### PR TITLE
connect using URI connection string support

### PR DESCRIPTION
**Pull request by kukoo1**
As mentioned in #73.
Typescript doesn't allow spreading arguments into function [https://github.com/Microsoft/TypeScript/issues/4130](https://github.com/Microsoft/TypeScript/issues/4130) and doesn't allow conditional super() call [https://github.com/Microsoft/TypeScript/issues/945](https://github.com/Microsoft/TypeScript/issues/945).

One way to achieve this is to instantiate Sequelize in a static factory function.
Old constructor must be removed to allow arguments to be exactly relayed to OriginSequelize constructor. Thus, this change will break backward compatability.

Developers currently using "new Sequelize(config)" have to change the code to "Sequelize.init(config)" or "Sequelize.init(URI, config)".

Should this be merged into next major version ?

### CODE REVIEW

**Comment by RobinBuschmann** [comment]
Hey @kukoo1 thanks for contributing :)

Why is spreading necessary here, from your point of view?

Did you try to resolve this with overloading the constructor like:
```typescript
export class Example {

  constructor(connection: string);
  constructor(options: Options);
  constructor(optionsOrConnection: Options|string) {
    /*...*/
  }
}
```
?

**Comment by kukoo1** [comment]
I've tried this.
```javascript
constructor(config: ISequelizeConfig, uri?: string) {
    // Sequelize constructor signature:
    //// new (database: string, username: string, password: string, options?: Options): Sequelize;
    //// new (database: string, username: string, options?: Options): Sequelize;
    //// new (uri: string, options?: Options): Sequelize;
   if (uri) {
      super(uri, BaseSequelize.prepareConfig(config));
   } else {
      super(
         (preparedConfig = BaseSequelize.prepareConfig(config), preparedConfig.name),
         preparedConfig.username,
         preparedConfig.password,
         preparedConfig
      );
   }
   this.init(config);
}
```
The compiler complains
`A 'super' call must be the first statement in the constructor when a class contains initialized properties`

So I tried solving with this.
```javascript
constructor(config: ISequelizeConfig, uri?: string) {
   super(
      uri || (preparedConfig = BaseSequelize.prepareConfig(config), preparedConfig.name),
      uri ? BaseSequelize.prepareConfig(config) : preparedConfig.username,
      uri ? undefined : preparedConfig.password,
      uri ? undefined : preparedConfig
    );
    this.init(config);
}
```
Now it works with traditional connection options as an object.
But by using connection string, it won't work.
Because originalSequelize will recognize that super(uri, config, undefined, undefined) contains 4 arguments, so "uri" would be db name, "config" would be username, "undefined" would be password and so on.

Any idea to this? :)

**Comment by RobinBuschmann** [comment]
@kukoo1 Thank you for your input :)

Or much simpler:
```typescript
new Sequelize({uri: '...'})
```
```typescript
constructor(config: ISequelizeConfig | ISequelizeUriConfig) {}
```
Since sequelize-typescript already uses one object literal for options instead of multiple parameters, I think this will be the most consistent approach. What do you think?

**Comment by BruceHem** [comment]
hmm it's just a string, do we really need to make it object literal?

**Comment by RobinBuschmann** [comment]
@BruceHem I think it is most likely, that the configuration will look like this

```typescript
new Sequelize({
  uri: '...',
  modelPaths: ['...']
})
``` 

But in addition, we could overload the constructor like:

```typescript
  constructor(connection: string);
  constructor(options: ISequelizeConfig | ISequelizeUriConfig);
  constructor(optionsOrConnection: ISequelizeConfig | ISequelizeUriConfig | string) {
    /*...*/
  }
```

**Comment by kukoo1** [comment]
I found the root of this mess.
I've just looked into Sequelize code.
It accepts
```javascript
new Sequelize({ ... options })
new Sequelize(URI, { ... options })
new Sequelize(database, username, password, { ... options })
```
So we could call super(uriOrOption) properly.

At first, when I coded this PR, I only looked at Sequelize.d.ts definition (@types/sequelize).
The definition accepts only
```javascript
new (uri: string, options?: Options)
new (database: string, username: string, options?: Options)
new (database: string, username: string, password: string, options?: Options)
```

So we've to open PR in DefinitelyTyped to add this beforehand
```javascript
new (options: Options): Sequelize;
```

**Comment by kukoo1** [comment]
Now I get into another trouble. I can't pass both URI and options at the same time.
current constructor looks like this
```javascript
constructor(configOrUri: ISequelizeConfig | ISequelizeUriConfig | string) {
   super(
      (typeof configOrUri === "string") ?
        configOrUri : // URI connection string
        BaseSequelize.prepareConfig(configOrUri) // config object
   );
}
```
Sequelize checks arguments using this code
```javascript
if (arguments.length === 1 && typeof database === 'object') {
   // new Sequelize({ ... options }) <-- in order THIS to WORKS, we must ONLY pass 1 argument !!
   // ...
} else if (arguments.length === 1 && typeof database === 'string' || arguments.length === 2 && typeof username === 'object') {
   // new Sequelize(URI, { ... options })
   // ...
}  else {  // <-- with this, URI string will NOT WORKING !!
   // new Sequelize(database, username, password, { ... options })
   // ...
}
```
So we couldn't do this.
```javascript
super(
   (typeof configOrUri === "string") ?
      configOrUri : // URI connection string
      BaseSequelize.prepareConfig(configOrUri), // config object
   (configOrUri.uri) ?
      configOrUri : // ISequelizeUriConfig
      undefined // <-- THIS will BREAK arguments.length === 1
);
```
There're 2 options.
1) ignore config when URI is passed (ISequelizeUriConfig will be a junk and we'll lose flexibility when use URI connection string)
2) open PR in Sequelize to add `const argLength = arguments.filter(val => val !== undefined).length` and use `if (argLength === 1)` instead.

**Comment by RobinBuschmann** [comment]
@kukoo1 Ahh ok, I see. I didn't get it in the first place.

From my understanding, typescript makes it impossible to use overloads in constructors in combination with inheritance in general. Cause it is very common to check arguments length. Or have we overseen something?

**Comment by kukoo1** [comment]
waiting for review ...
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18896

**Comment by kukoo1** [comment]
@RobinBuschmann  I committed the new one.
```javascript
constructor(config: ISequelizeConfig | ISequelizeUriConfig | ISequelizeDbNameConfig);
constructor(uri: string);
```

I suggest to deprecate "name" property in options, and use "database" instead.
Because, in Sequelize documentation, "database" is used.
In order to use the same config when switching from ordinary sequelize, we should use "database".
What's your opinion ?

**Comment by RobinBuschmann** [comment]
Looks good to me. Deprecating "name"  is reasonable as well. But instead of adding "@Todo", you could write "@deprecated" - this will be noticed by many IDEs and therefore be notice the user that "name" is deprecated.

**Comment by RobinBuschmann** [comment]
Fixes #73

**Pull request merged**
