### PR TITLE
Upgrade to Sequelize 6.1.1

### PR DESCRIPTION
**Pull request by awais000**
image

Upgraded to latest Sequlize which is at the moment v6.2
Executed and passed all the tests on every version after v5.22

Due to the depreciation of BlueBird, most of the breaking changes were in tests.
Other than that change in name of some function and typing compatibly.

### CODE REVIEW

**Comment by kf6kjg** [comment]
Good job.  Looks like it's mostly a subset of the changes from #787 - with some minor stylistic difference. Quickly comparing the two, I find a few files that I'd changed that you did not. Most likely the target moved: 6.0.0 beta 6 vs 6.2. Any thoughts?

I'm still in crunch until the 15th or so, so I've only been pushing patches to projects that are causing active breakage in the code I'm working on - and I've not yet had the time to upgrade deps on the project past the 6 beta...  If this PR is able to get things fixed I'm all for it!

**Comment by ShaharHD** [comment]
quick note, can the sequelize version be `^6.2.4` to allow future minor changes?

**Comment by awais000** [comment]
> Good job. Looks like it's mostly a subset of the changes from #787 - with some minor stylistic difference. Quickly comparing the two, I find a few files that I'd changed that you did not. Most likely the target moved: 6.0.0 beta 6 vs 6.2. Any thoughts?
> 
> I'm still in crunch until the 15th or so, so I've only been pushing patches to projects that are causing active breakage in the code I'm working on - and I've not yet had the time to upgrade deps on the project past the 6 beta... If this PR is able to get things fixed I'm all for it!

Everything looks fine and running without any problems.  I almost read sequallize all changelogs releases by release. I tried to change minimum code to accommodate new the changes and pass all the tests.

**Comment by awais000** [comment]
> quick note, can the sequelize version be `^6.2.4` to allow future minor changes?

Yes. Infact I'm currently running ^6.2.4. I just excluded minor changes version. Sorry for that @ShaharHD

**Comment by juhoojala** [comment]
Getting this merged & released would be highly appreciated :+1:

Does someone btw have knowledge on which versions of typescript are compatible?

**Comment by sudhagar10** [comment]
Hi, any update on when this will be merged and pushed to Npm?

**Comment by brianschardt** [comment]
@RobinBuschmann can we get this merged in?

**Comment by RobinBuschmann** [comment]
@awais000 @kf6kjg thanks for upgrading and i'm very sorry for the delay.

**Comment by RobinBuschmann** [comment]
@awais000 Didn't noticed it in the first place. Why did you delete the package-lock.json?

**Comment by RobinBuschmann** [comment]
I've published a new version (`sequelize-typescript@2.0.0-beta.0` or just `sequelize-typescirpt@next`). Let me know if everything works fine with it

**Comment by bianchi** [comment]
> I've published a new version (`sequelize-typescript@2.0.0-beta.0` or just `sequelize-typescirpt@next`). Let me know if everything works fine with it

Have been using since you posted and everything is working until now. Thank you

**Comment by awais000** [comment]
> @awais000 Didn't noticed it in the first place. Why did you delete the package-lock.json?


> @awais000 @kf6kjg thanks for upgrading and i'm very sorry for the delay.

No problem. I'm personally using this package for a project.. Great repository and great work on your side.

**Comment by mankinchi** [comment]
hi, just wondering whether this is supporting v6 now? As the readme on both github and NPM are stating for the support of Sequelize v5

**Comment by luiz290788** [comment]
Was this released? It is merged but it seems it isn't part of the latest release.

**Comment by mankinchi** [comment]
hi @RobinBuschmann , any news on the release?

**Comment by cyrilchapon** [comment]
Up

**Comment by Divlo** [comment]
The pull-request was merged but not released in npm yet.
Is it working with the latest version of Sequelize (currently 6.3.4) ?
Looking forward to have the support of Sequelize v6+ with `sequelize-typescript`.

**Comment by ricardoafonfaria** [comment]
use `npm i sequelize-typescript@next`

**Comment by mankinchi** [comment]
am I right to assume that the sequelize-typescript v2 is only in beta and not fully release yet?

**Pull request merged**
