### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mossaabzaroui**
@RobinBuschmann 

Fix file extension for model import.

### CODE REVIEW

**Comment by RobinBuschmann** [comment]
Hey @mossaabzaroui thanks for contributing, but actually `*.ts` is not wrong, when using `ts-node`, `ts` files can be loaded directly. Probably mention both (usage with `*.js` AND `*.ts`) and making a hint to `ts-node` would make sense. What do you think?

**Comment by mossaabzaroui** [comment]
@RobinBuschmann 
- Are you suggesting to change ts-config to point Typescript which extention file should be used instead of changing the current modelsPath ?

- When i use .ts extension i have this error : Model not initialized: "<Model Name>" needs to be added to a Sequelize instance before "create" can be called. Did you have any idea about this issue ?

**Comment by RobinBuschmann** [comment]
Regarding Your last point: can you provide an example?

**Comment by RobinBuschmann** [comment]
Close this issue due to no activity

**Pull request closed without merging**
