### PR TITLE
Added generic types for scope decorators

### PR DESCRIPTION
**Pull request by nmussy**
This PR allows typing the scope decorators, to allow stricter type checking:

```ts
@DefaultScope<Person>({
  attributes: ['id'],
  where: {id: 'foo'}
})
@Scopes<Person>({
  bar: {
    attributes: ['id']
  }
})
@Table
export class Person extends Model<Person> {

  @PrimaryKey
  id: string;
}
```

The tests are all passing, but it's dependent on another PR for [@types/sequelize](/DefinitelyTyped/DefinitelyTyped/tree/master/types/sequelize), [PR 22755](/DefinitelyTyped/DefinitelyTyped/pull/22755), which is currently opened.

I haven't added any additional tests yet, and I'd very much appreciate the help!

### CODE REVIEW

**Comment by nmussy** [comment]
The PR was approved on [@types/sequelize](/DefinitelyTyped/DefinitelyTyped/tree/master/types/sequelize), and I've bumped the version on my PR accordingly. All existing tests are passing. 

This PR also makes #262 unnecessary.

**Comment by TitaneBoy** [comment]
@nmussy . You PR looks to break what worked before.

When something like: Model.findAll({attributes: ['id', 'name']}) worked before, your changes breaks previous behavior...How to make it work with your changes ?

Thanks

**Comment by nmussy** [comment]
Discussed [here](/DefinitelyTyped/DefinitelyTyped/pull/22755#issuecomment-356383817), as the breaking change was made on [@types/sequelize](/DefinitelyTyped/DefinitelyTyped/tree/master/types/sequelize).

**Comment by nmussy** [comment]
I've just opened a revert for [@types/sequelize#22755](/DefinitelyTyped/DefinitelyTyped/pull/22755), which is pretty much going to kill this PR in its current state.

Maybe the changes I applied to DefinitelyTyped could be incorporated here instead, but it'd be a shame to have them miss on these stronger typings.

Any suggestion would be greatly appreciated, and thanks again @TitaneBoy for the help.

**Comment by TitaneBoy** [comment]
Thanks @nmussy  for your quick response and your understanding

**Comment by RobinBuschmann** [comment]
@nmussy Do I understand this correctly: There is an issue with the typings, which blocks this PR from getting merged?

**Comment by nmussy** [comment]
Yes, the added scope generic wouldn't have any effect if the
`FindOptionsAttributesArray` type isn't strongly enforced. I haven't had
time to look into into again, but we can close this PR in the meantime.

**Pull request closed without merging**
