### PR TITLE
Add dataValues to Model.d.ts

### PR DESCRIPTION
**Pull request by santiagodoldan**

### CODE REVIEW

**Comment by santiagodoldan** [comment]
https://github.com/RobinBuschmann/sequelize-typescript/issues/252

**Comment by santiagodoldan** [comment]
@RobinBuschmann is this ok? at least it works as expected 😂

**Comment by RobinBuschmann** [comment]
Hey @santiagodoldan, thanks for implementing. Since the last merge we do have a type called `GetAttributes<T>`, which omits the methods from the Model Interface and does only provide what comes from T and `{id?: number|any; createdAt?: Date|any; updatedAt?: Date|any; deletedAt?: Date|any; version?: number|any;}` I think this would be a more suitable interface.What do you think? :)

**Comment by santiagodoldan** [comment]
Got these error messages `Property 'id' does not exist on type 'GetAttributes<User>'. Property 'id' does not exist on type 'Partial<Omit<User, "id" | "$add" | "$set" | "$get" | "$count" | "$create" | "$has" | "$remove" | ...'` or `Property 'customAttr' does not exist on type 'GetAttributes<User>'. Property 'customAttr' does not exist on type '{ id?: any; createdAt?: any; updatedAt?: any; deletedAt?: any; version?: any; }'.`

**Comment by santiagodoldan** [comment]
We're using `@Column` to define them, could be that an issue?

```
  @PrimaryKey
  @Column({ autoIncrement: true })
  public id: number
```

**Comment by RobinBuschmann** [comment]
@santiagodoldan Hmm... good questions. I couldn't find out yet. I will come back to you, when I know what the problem is.

**Comment by RobinBuschmann** [comment]
@santiagodoldan Ok, should be fixed now. Additionally I've renamed the type. Can you give it another try? :)

**Comment by santiagodoldan** [comment]
@RobinBuschmann yep, works ok now, thanks

**Pull request closed without merging**
