### PR TITLE
Fix scope type

### PR DESCRIPTION
**Pull request by bilby91**

### CODE REVIEW

**Comment by bilby91** [comment]
Should fix #113 . Please verify @RobinBuschmann if this is correct please!

**Comment by RobinBuschmann** [comment]
Hey, thanks for fixing this. :)  Why do you add `<T extends Model<T>`? The generic isn't used in the signature of `scope`. Or do I overseen something?

**Comment by bilby91** [comment]
@RobinBuschmann you are right. I originally thought that WhereOptions where of type `<T extends Model<T>`, then realized it's used as `any` on the other places. Will change that.

**Comment by RobinBuschmann** [comment]
closes #113

**Comment by bilby91** [comment]
@RobinBuschmann Can we do a beta.1 ?

**Comment by RobinBuschmann** [comment]
It's done :)

**Pull request merged**
