### PR TITLE
Add missing ICreateOptions

### PR DESCRIPTION
**Pull request by bilby91**

### CODE REVIEW

**Comment by bilby91** [comment]
I'm trying to run my project pointing to the github repository but it doesn't seem to build the code when installing. How can I install the package from my branch ?

**Comment by RobinBuschmann** [comment]
hey thanks for contributing!

So you want to `npm install path/to/github/repo`, right?
You could create another branch which includes the compiled files and install this branch. The master only consists of *.ts files.

**Comment by bilby91** [comment]
@RobinBuschmann Thank you for this awesome project!

I just migrated our code base from `Model<Instance<T>, T> => Model<T>`. At first I was confused, I thought I had to use the `sequelize` packages types. Then I realized that I can use directly the `sequelize-typescript` Model typings :).

Yep, I want to do that. I guess I can wait for a little. Any release coming soon ?

**Comment by RobinBuschmann** [comment]
Thank you.

I'm planing to release a beta version next weekend.

**Pull request merged**
