### PR TITLE
Export ISequelizeUriConfig

### PR DESCRIPTION
**Pull request by bilby91**

### CODE REVIEW

**Comment by bilby91** [comment]
@RobinBuschmann Hey, added a missing export.

**Comment by RobinBuschmann** [comment]
Thanks for adding

**Comment by bilby91** [comment]
@RobinBuschmann Any chance on getting a new beta ? :)

**Comment by RobinBuschmann** [comment]
@bilby91 Its done (`0.6.0-beta.5`)

Off topic: Hey @bilby91 and @snewell92 Are you interested in being collaborators of this project? So that you would have the right to write to this repo?

**Comment by bilby91** [comment]
Thanks!

Yes, for sure! Really interested!

Martín

**Comment by RobinBuschmann** [comment]
Cool :) I Would suggest to work with [gitflow](http://nvie.com/posts/a-successful-git-branching-model/) then. Additionally we should request each other as reviewers for PRs. What do you think?

**Comment by bilby91** [comment]
Sounds good! Let's start working that way then! 

Side comment. I'm starting a different project now that is related to this orm / sequelize world. Would love some input from you and help if you want to. I tried to email you a few weeks ago but not sure if you got my email!

Martín

**Comment by RobinBuschmann** [comment]
Sry, didn’t noticed an email. What’s your email address? Or could you send it again? I’d really like to help you :)

**Comment by bilby91** [comment]
No problem!

fmartin91@gmail.com

Write me!

Martín

**Comment by RobinBuschmann** [comment]
I checked my mail inbox. I didn't get an email from you. Do you like to send it again? I've sent you an email to ensure you got my mail address.

**Pull request merged**
