### PR TITLE
compatibility updates for sequelize >=6.2

### PR DESCRIPTION
**Pull request by lukashroch**
Types compatibility updates for sequelize >=6.2

- [x] Build OK
- [x] Tests OK

This updates type changes introduced in sequelize >=6.2 ([https://github.com/sequelize/sequelize/commit/871157bc07ccdbf2445581b8becd297ede887c22](url))

### CODE REVIEW

**Comment by Benjamin-Gardien** [comment]
Pleaseeeeeeeeee @RobinBuschmann  🐒🙏🏼

**Comment by niloyc** [comment]
@RobinBuschmann please merge if all ok...

**Comment by lukashroch** [comment]
@RobinBuschmann can you merge for next beta to let people test?

If all OK, happy to prepare PR to update README to reflect new sequelize changes and probably remote old-style scopes. They were already deprecated since v1, so I think it could be removed for v2 and sequelize v6.

**Comment by Benjamin-Gardien** [comment]
@RobinBuschmann the man who is the most wanted in Github story 😂 😂 😂 😂 😂 😂

**Comment by paolocattani** [comment]
@RobinBuschmann are you still following this project? Have you considered transfer ownership to someone?
Lots of nice guys are trying to keep this project updated.

**Comment by Benjamin-Gardien** [comment]
@kamilmysliwiec @BrunnerLivio @fwoelffel @jmcdo29 @johnbiundo @MarkPieszak @nartc @ThomRick  @valorkin Hello guys 👋🏼  Do you think about a fork of this project ? This package it's a big part of a good integration between NestJs and Sequelize for typescript usage 🧐 I think @RobinBuschmann no longer follows this project 🤔 There is no release since this summer (moreover it's a beta). 😞

**Comment by niloyc** [comment]
@paolocattani  @Benjamin-Gardien I think he is still active in github, I tried reaching out through another repo...

**Comment by Benjamin-Gardien** [comment]
@RobinBuschmann thank you 🎉

**Comment by RobinBuschmann** [comment]
Sorry guy, this year was a really tough one for me and I'm afraid I won't have much time in the near future. But I'm still highly interested in keeping this project up. So help is very much appreciated. I would really like to add collaborators to this project. If anyone is interested and can show some references in open-source development..? I know that collaborators won't be enough, since sequelize-typescript runs under my npm account. So that the release process requires to be automated via github as well.

**Comment by RobinBuschmann** [comment]
I've just released a new beta... also available with @next: [sequelize-typescript@2.0.0-beta.1](https://www.npmjs.com/package/sequelize-typescript/v/2.0.0-beta.1) Any feedback would be very nice

Thank you @lukashroch very much for implementing. Nice work 👍

**Comment by Benjamin-Gardien** [comment]
@QuanticPotatoes and me are interested to help you to maintain this project but we don't really have experience in Open source projet 😞  Only @QuanticPotatoes participated 3 years ago to an open source project. Usually, we built application for private company 🤷🏼‍♂️  Maybe it's time for us to try ! It will be a pleasure to try to help you 😃

**Comment by luiz290788** [comment]
> @QuanticPotatoes and me are interested to help you to maintain this project but we don't really have experience in Open source projet 😞 Only @QuanticPotatoes participated 3 years ago to an open source project. Usually, we built application for private company 🤷🏼‍♂️ Maybe it's time for us to try ! It will be a pleasure to try to help you 😃

I'm also interested. I have a little of experience with open source but we are really interested in helping in the project.

**Comment by RobinBuschmann** [comment]
@goalia @luiz290788 thanks. I think any advanced contributions to this project would be a good reference :)

@lukashroch, what about you? Are you interested in being added as a collaborator to this project?

**Comment by goalia** [comment]
@RobinBuschmann maybe we can make a call with @luiz290788 and @lukashroch and also with my co founder @QuanticPotatoes ? 😊

**Comment by lukashroch** [comment]
@RobinBuschmann sure, happy to help out! 👍

**Pull request merged**
