### PR TITLE
Add paranoid in IncludeOptions interface

### PR DESCRIPTION
**Pull request by pirmax**

### CODE REVIEW

**Comment by pirmax** [comment]
@RobinBuschmann What is missing to do the tests in Travis? I just added a line in the code, why did it fail?

**Comment by RobinBuschmann** [comment]
I will look into this soon. This is an issue with `sqlite3` #236

**Comment by RobinBuschmann** [comment]
Thanks for fixing this :)

**Comment by pirmax** [comment]
Thank you, thanks to update your NPM version ;)

**Comment by RobinBuschmann** [comment]
Done ;) `sequelize-typescript@0.6.2`

**Comment by pirmax** [comment]
@RobinBuschmann Thank you very much, the dev. team here thanks you!

**Pull request merged**
