### PR TITLE
Update glob version from 7.1.2 to 7.1.6

### PR DESCRIPTION
**Pull request by batmanhit**
Update "glob" package version for 0.6.X.

### CODE REVIEW

**Comment by Divlo** [comment]
Hey! @batmanhit 
There is already a PR for this change, see #871.

**Comment by batmanhit** [comment]
Wow, Cool. Thanks for letting me know.
I am going to close this PR then.

**Comment by batmanhit** [comment]
@Divlo Btw, is this for `0.6.X` version or `1.X` or `2.X` version?
Because we are using `0.6.X` at the moment and we have no immediate plan to update `sequelize-typescript` version.

**Comment by Divlo** [comment]
@batmanhit Oh right, it's for the latest (currently beta) version.
You should update `sequelize-typescript` and if everything is going well, hopefully we can have `sequelize-typescript@2.0.0` as stable release soon.

**Comment by batmanhit** [comment]
Cool, In that case for now, let's close this one and I will wait for your updates. Thanks, @Divlo

**Pull request closed without merging**
