### PR TITLE
narrow down types for attributes passed to functions like Model.create/Model.build etc

### PR DESCRIPTION
**Pull request by Danlock**
for issue https://github.com/RobinBuschmann/sequelize-typescript/issues/239
I wanted to typecheck upsert values as well, but it doesn't seem to have a generic overloaded method like all the others.

### CODE REVIEW

**Comment by RobinBuschmann** [comment]
@Danlock Thanks for implementing :) I will look at it very soon!

**Comment by RobinBuschmann** [comment]
@Danlock Thanks again for your implementation. Looks good to me. There is one question left from my side: Why do you name the type `GetAttributes`? Why not `ModelAttributes` or something like that? :)

**Comment by Danlock** [comment]
Because rather than simply listing the models attributes, it gets attributes from a model. More of a function than a type really.

**Comment by RobinBuschmann** [comment]
@Danlock I would be more happy with `ModelAttributes` or so. But lets do this later. I will merge it. Thank you very much :)

**Comment by Danlock** [comment]
Maybe ParsedModelAttributes or FilteredModelAttributes? Thanks for merging.

**Comment by RobinBuschmann** [comment]
`FilteredModelAttributes` sounds good :)

**Pull request merged**
