### PR TITLE
feature(hooks): add decorators for declaring hooks

### LINKED ISSUE #88: A `@Hook` decorator would be great
There are several ways to add hooks, but they need your `Model` to be added to a Sequelize instance first. It isn’t very declarative.

It would be great if there was a `@Hook` decorator. Something like:

```typescript
@Table
class Book extends Model<Book> {
  // (bunch of @Columns etc.)

  @Hook('beforeCreate')
  static reticulateSplines(instance: Book) {
    // do beforeCreate hook stuff here
  }

  @Hook('afterDestroy')
  static herdLlamas(instance: Book) {
    // do afterDestroy hook stuff here
  }
}
```

Is this in the works? I could try to write something. The decorator would store information using the `reflect-metadata` system and then something like `initializeHooks` would be called from the `addModels` method.

### PR DESCRIPTION
**Pull request by natesilva**
I had to re-do the pull request after I botched the original branch. The only change is that this centralizes the hook implementation logic into the hooks services file.

Fixes #88, replaces #97.

### CODE REVIEW

**Comment by natesilva** [comment]
Thank you!

**Comment by RobinBuschmann** [comment]
Thank you for implementing this. It's a great feature!

**Comment by RobinBuschmann** [comment]
I've made a beta release, in which this feature is included now :)

`npm install sequelize-typescript@0.5.0-beta.0`

**Comment by mengkheang** [comment]
@RobinBuschmann can I use an async function like this?

```javascript
  @BeforeUpdate
  @BeforeCreate
  static async hashPassword(instance: User) {
    // this will be called when an instance is created or updated
    instance.password = await bcrypt.hash(instance.password, 10);
  }
```

**Comment by natesilva** [comment]
@mengkheang Yes. A hook function may return a `Promise`, so `async` functions are fine. http://docs.sequelizejs.com/manual/tutorial/hooks.html#declaring-hooks

**Comment by mengkheang** [comment]
@natesilva thank for the explaining :)

**Comment by RobinBuschmann** [comment]
`sequelize-typescript@0.5.0` is released now 🎉

**Comment by natesilva** [comment]
Thank you!

**Pull request merged**
