### PR TITLE
Add NotEmpty validation message

### PR DESCRIPTION
**Pull request by gloorx**

### CODE REVIEW

**Comment by RobinBuschmann** [comment]
@gloorx thanks for adding this :) You need to add some overloads to make the compiler happy. See this as an example: https://github.com/RobinBuschmann/sequelize-typescript/blob/master/lib/annotations/AllowNull.ts

**Comment by gloorx** [comment]
I'll fix it

**Comment by RobinBuschmann** [comment]
Hey @gloorx, any progress on this? Do you need some help?

**Comment by gloorx** [comment]
Where can I add more tests about NotEmpty? Thank you.

**Comment by RobinBuschmann** [comment]
`test/specs/validation.spec.ts`:

```typescript
 describe('validation', () => {
  // ...
  describe('decorators', () => {
    // ...
    describe('NotEmpty', () => {
      // tests goes here :)
    });
  });
});
```

**Pull request merged**
