### PR TITLE
Bump prepare test script sequelize versions

### LINKED ISSUE #29: Sequelize Officially released 4.1.0
```
$ npm ls sequelize version

  + sequelize@4.1.0                         
  added 19 packages in 7.347s               
  newhotness@0.0.0 C:\dorianRepos\newhotness
  `-- sequelize@4.1.0                       
```

Looks like sequelize has officially been updated in the npm registry. We should target the latest stable versions for testing. Here are all the versions of sequelize above `3.30.0`:

```
$ npm view sequelize@'>3.30.0' version 
sequelize@3.30.1 '3.30.1'              
sequelize@3.30.2 '3.30.2'              
sequelize@3.30.3 '3.30.3'              
sequelize@3.30.4 '3.30.4'              
sequelize@4.0.0 '4.0.0'                
sequelize@4.1.0 '4.1.0'                
```

I propose `package.json` be changed to target `3.30.4` and `4.1.0` in the prepare scripts. I'll make a PR and link it. I'm mostly interested in getting rid of `npm install sequelize@4.0.0-1` now that most people installing sequelize from now on will get `4.1.0`.

My initial attempts yielded one failed test in the v4 tests. Line 995 of `model.spec.ts` - the test where it `throws an error if no where clause is given`. Maybe something changed? I'll look into it. v3 tests ran fine.

### PR DESCRIPTION
**Pull request by snewell92**
Bump up sequelize versions to latest stable ones.

Closes #29

### CODE REVIEW

**Comment by snewell92** [comment]
A test is failing, not sure why, I've been looking at the new sequelize docs but can't see anything that would indicate different behavior in the model sync methods.

Future reference: file `test/specs/model-spec.ts` line ~**1004**.

**Comment by snewell92** [comment]
Travis CI has the same test failing. Something has changed - not sure if the behavior the test is looking for has been removed, or if a new syntax is needed.

**Comment by RobinBuschmann** [comment]
Looks like the wording of the error message has changed:
> `AssertionError: expected 'Missing where attribute in the options parameter' to equal 'Missing where attribute in the options parameter passed to update.'`

The test expects 'Missing where attribute in the options parameter', but it throws 'Missing where attribute in the options parameter passed to update.'.

**Comment by snewell92** [comment]
Ah, the sequelize team did change the error message.

Okay, in version 3 it still is the old error message, so I can just switch the test to matching against a regex.

```
expect(err.message).to.match(/^Missing where attribute in the options parameter/);
```

Otherwise I would need some way for the test to know whether it is version 3 or 4. (Does sequelize expose a version variable?)

**Comment by snewell92** [comment]
@RobinBuschmann 

Got it passing 😄

**Pull request merged**
